# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170301_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 3, 2, 18, 8, 53, 137305, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
