# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170302_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 3, 5, 19, 9, 7, 102417, tzinfo=utc)),
        ),
    ]
