# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170305_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 3, 5, 19, 29, 6, 607125, tzinfo=utc)),
        ),
    ]
